// <auto-generated />
using ControlPlane.Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ControlPlane.Api.Migrations
{
    [DbContext(typeof(ControlPlaneDbContext))]
    [Migration("20260621104914_WidenByteColumns")]
    partial class WidenByteColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ControlPlane.Api.Database.Tables.CPU", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MetricId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MetricId")
                        .IsUnique();

                    b.ToTable("CPU_Header", (string)null);
                });

            modelBuilder.Entity("ControlPlane.Api.Database.Tables.CPUDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CPUID")
                        .HasColumnType("integer");

                    b.Property<double>("CPUUsage")
                        .HasColumnType("double precision");

                    b.Property<int>("HeaderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HeaderId");

                    b.ToTable("CPU_Details", (string)null);
                });

            modelBuilder.Entity("ControlPlane.Api.Database.Tables.Disk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("Free")
                        .HasColumnType("bigint");

                    b.Property<int>("MetricId")
                        .HasColumnType("integer");

                    b.Property<long>("Total")
                        .HasColumnType("bigint");

                    b.Property<long>("Used")
                        .HasColumnType("bigint");

                    b.Property<double>("UsedPercent")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("MetricId")
                        .IsUnique();

                    b.ToTable("Disk", (string)null);
                });

            modelBuilder.Entity("ControlPlane.Api.Database.Tables.Host", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BootTime")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("HostID")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Kernal")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("OS")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Platform")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("PlatformFamily")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("PlatformVersion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Uptime")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.ToTable("Host", (string)null);
                });

            modelBuilder.Entity("ControlPlane.Api.Database.Tables.Memory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("Available")
                        .HasColumnType("bigint");

                    b.Property<long>("Free")
                        .HasColumnType("bigint");

                    b.Property<int>("MetricId")
                        .HasColumnType("integer");

                    b.Property<long>("Total")
                        .HasColumnType("bigint");

                    b.Property<long>("Used")
                        .HasColumnType("bigint");

                    b.Property<double>("UsedPercent")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("MetricId")
                        .IsUnique();

                    b.ToTable("Memory", (string)null);
                });

            modelBuilder.Entity("ControlPlane.Api.Database.Tables.Metrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HostId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HostId");

                    b.ToTable("Metrics", (string)null);
                });

            modelBuilder.Entity("ControlPlane.Api.Database.Tables.Network", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MetricId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MetricId")
                        .IsUnique();

                    b.ToTable("Network", (string)null);
                });

            modelBuilder.Entity("ControlPlane.Api.Database.Tables.NetworkDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("BytesReceived")
                        .HasColumnType("bigint");

                    b.Property<long>("BytesSent")
                        .HasColumnType("bigint");

                    b.Property<int>("NetworkId")
                        .HasColumnType("integer");

                    b.Property<string>("NetworkName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<long>("PacketsReceived")
                        .HasColumnType("bigint");

                    b.Property<long>("PacketsSent")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("NetworkId");

                    b.ToTable("Network_Details", (string)null);
                });

            modelBuilder.Entity("ControlPlane.Api.Database.Tables.CPU", b =>
                {
                    b.HasOne("ControlPlane.Api.Database.Tables.Metrics", "RecordHeader")
                        .WithOne("CPU")
                        .HasForeignKey("ControlPlane.Api.Database.Tables.CPU", "MetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecordHeader");
                });

            modelBuilder.Entity("ControlPlane.Api.Database.Tables.CPUDetails", b =>
                {
                    b.HasOne("ControlPlane.Api.Database.Tables.CPU", "Header")
                        .WithMany("Details")
                        .HasForeignKey("HeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Header");
                });

            modelBuilder.Entity("ControlPlane.Api.Database.Tables.Disk", b =>
                {
                    b.HasOne("ControlPlane.Api.Database.Tables.Metrics", "RecordHeader")
                        .WithOne("Disk")
                        .HasForeignKey("ControlPlane.Api.Database.Tables.Disk", "MetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecordHeader");
                });

            modelBuilder.Entity("ControlPlane.Api.Database.Tables.Memory", b =>
                {
                    b.HasOne("ControlPlane.Api.Database.Tables.Metrics", "RecordHeader")
                        .WithOne("Memory")
                        .HasForeignKey("ControlPlane.Api.Database.Tables.Memory", "MetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecordHeader");
                });

            modelBuilder.Entity("ControlPlane.Api.Database.Tables.Metrics", b =>
                {
                    b.HasOne("ControlPlane.Api.Database.Tables.Host", "Host")
                        .WithMany("Metrics")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Host");
                });

            modelBuilder.Entity("ControlPlane.Api.Database.Tables.Network", b =>
                {
                    b.HasOne("ControlPlane.Api.Database.Tables.Metrics", "RecordHeader")
                        .WithOne("Network")
                        .HasForeignKey("ControlPlane.Api.Database.Tables.Network", "MetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecordHeader");
                });

            modelBuilder.Entity("ControlPlane.Api.Database.Tables.NetworkDetails", b =>
                {
                    b.HasOne("ControlPlane.Api.Database.Tables.Network", "Header")
                        .WithMany("Details")
                        .HasForeignKey("NetworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Header");
                });

            modelBuilder.Entity("ControlPlane.Api.Database.Tables.CPU", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("ControlPlane.Api.Database.Tables.Host", b =>
                {
                    b.Navigation("Metrics");
                });

            modelBuilder.Entity("ControlPlane.Api.Database.Tables.Metrics", b =>
                {
                    b.Navigation("CPU")
                        .IsRequired();

                    b.Navigation("Disk")
                        .IsRequired();

                    b.Navigation("Memory")
                        .IsRequired();

                    b.Navigation("Network")
                        .IsRequired();
                });

            modelBuilder.Entity("ControlPlane.Api.Database.Tables.Network", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
